const div = dom.create('<div>666</div>')
const node1 = document.querySelector('div')
console.log(node1.parentElement)
dom.after(node1, div)
dom.empty(empty)
dom.attr(node1,'title','123')
console.log(dom.attr(node1,'title'))
dom.text(node1,'testetext')
dom.style(node1,{border:'1px solid red',color:'blue'})
dom.style(node1,'font-size','50px')
console.log(dom.style(node1,'border'))
dom.class.add(node1,'red')
console.log(dom.class.has(node1,'red'))
dom.class.remove(node1,'red')
fn=()=>{
    alert('click')
}
dom.on(node1,'click',fn)
dom.off(node1,'click',fn)